module i2s_reciever_config_wrap (
    input  wire         s_axi_ctrl_aclk,
	input  wire         s_axi_ctrl_aresetn,
	output wire         s_axi_ctrl_awvalid,
	input  wire         s_axi_ctrl_awready,
	output wire  [7:0]  s_axi_ctrl_awaddr,
	output wire         s_axi_ctrl_wvalid,
	input  wire         s_axi_ctrl_wready,
	output wire  [31:0] s_axi_ctrl_wdata,
	output wire         s_axi_ctrl_arvalid,
	input  wire         s_axi_ctrl_arready,
	output wire  [7:0]  s_axi_ctrl_araddr,
	input  wire         s_axi_ctrl_rvalid,
	output wire         s_axi_ctrl_rready,
	input  wire [31:0]  s_axi_ctrl_rdata,
	input  wire [1:0]   s_axi_ctrl_rresp,
	input  wire         s_axi_ctrl_bvalid,
	output wire         s_axi_ctrl_bready,
	input  wire [1:0]   s_axi_ctrl_bresp);
    
    i2s_reciever_config i2s_reciever_config0(
        .s_axi_ctrl_aclk(s_axi_ctrl_aclk),
        .s_axi_ctrl_aresetn(s_axi_ctrl_aresetn),
        .s_axi_ctrl_awvalid(s_axi_ctrl_awvalid),
        .s_axi_ctrl_awready(s_axi_ctrl_awready),
        .s_axi_ctrl_awaddr(s_axi_ctrl_awaddr),
        .s_axi_ctrl_wvalid(s_axi_ctrl_wvalid),
        .s_axi_ctrl_wready(s_axi_ctrl_wready),
        .s_axi_ctrl_wdata(s_axi_ctrl_wdata),
        .s_axi_ctrl_arvalid(s_axi_ctrl_arvalid),
        .s_axi_ctrl_arready(s_axi_ctrl_arready),
        .s_axi_ctrl_araddr(s_axi_ctrl_araddr),
        .s_axi_ctrl_rvalid(s_axi_ctrl_rvalid),
        .s_axi_ctrl_rready(s_axi_ctrl_rready),
        .s_axi_ctrl_rdata(s_axi_ctrl_rdata),
        .s_axi_ctrl_rresp(s_axi_ctrl_rresp),
        .s_axi_ctrl_bvalid(s_axi_ctrl_bvalid),
        .s_axi_ctrl_bready(s_axi_ctrl_bready),
        .s_axi_ctrl_bresp(s_axi_ctrl_bresp)
    );
endmodule